In [144]:
import pandas as pd
import matplotlib.pyplot as plt

### Converting to Features Format

In [145]:
cf = pd.read_csv("../Datasets/John_Hopkins/Clean/confirmed_daily.csv", index_col=0)
df = pd.read_csv("../Datasets/John_Hopkins/Clean/deaths_daily.csv", index_col=0)
rf = pd.read_csv("../Datasets/John_Hopkins/Clean/recovered_daily.csv", index_col=0)

In [146]:
cf = cf.reset_index()
cf = cf.melt(id_vars="Date")
cf.columns = ["date", "country", "confirmed"]

In [147]:
cf.head(10)

      date      country  confirmed
0  1/22/20  Afghanistan        0.0
1  1/23/20  Afghanistan        0.0
2  1/24/20  Afghanistan        0.0
3  1/25/20  Afghanistan        0.0
4  1/26/20  Afghanistan        0.0
5  1/27/20  Afghanistan        0.0
6  1/28/20  Afghanistan        0.0
7  1/29/20  Afghanistan        0.0
8  1/30/20  Afghanistan        0.0
9  1/31/20  Afghanistan        0.0

In [148]:
df = df.reset_index()
df = df.melt(id_vars="Date")
df.columns = ["date", "country", "deaths"]

In [149]:
rf = rf.reset_index()
rf = rf.melt(id_vars="Date")
rf.columns = ["date", "country", "recovered"]

In [150]:
cf["recovered"] = rf["recovered"]
cf["deaths"] = df["deaths"]

In [151]:
cf.to_csv("../Datasets/features_format.csv")

In [152]:
df = cf

### Adding Country Codes

In [153]:
c_dict = pd.read_csv("../country_dict.csv")

In [154]:
c_dict["country"] = c_dict["country"].str.replace("_", " ")
c_dict = c_dict.set_index("country")
c_dict.head(5)

            code
country
Afghanistan  AFG
Albania      ALB
Algeria      DZA
Andorra      AND
Angola       AGO

In [155]:
code_dict = c_dict.to_dict()['code']

In [156]:
dict_entries = set(code_dict.keys())
df_entries = set(df["country"].unique())

In [157]:
df_entries.difference(dict_entries)

{'Brunei',
 'Burma',
 'Cabo Verde',
 'Congo (Brazzaville)',
 'Congo (Kinshasa)',
 "Cote d'Ivoire",
 'Curacao',
 'Diamond Princess',
 'Guinea-Bissau',
 'Korea, South',
 'MS Zaandam',
 'Taiwan*',
 'Tanzania',
 'Timor-Leste',
 'Turks and Caicos Islands',
 'US',
 'West Bank and Gaza',
 'Western Sahara'}

In [158]:
dict_entries.difference(df_entries)

{'Brunei Darussalam',
 'Cape Verde',
 'Congo',
 'Cote dIvoire',
 'Cura√ßao',
 'Democratic Republic of the Congo',
 'Guam',
 'Guernsey',
 'Guinea Bissau',
 'Jersey',
 'Myanmar',
 'Northern Mariana Islands',
 'Palestine',
 'Puerto Rico',
 'South Korea',
 'Taiwan',
 'Timor Leste',
 'Turks and Caicos islands',
 'United Republic of Tanzania',
 'United States Virgin Islands',
 'United States of America'}

In [162]:
correction_dict = {
    "Brunei": "Brunei Darussalam",
    "Burma": "Myanmar",
    "Cabo Verde": "Cape Verde",
    "Congo (Brazzaville)": "Congo",
    "Congo (Kinshasa)": "Democratic Republic of the Congo",
    "Cote d'Ivoire": "Cote dIvoire",
    "Guinea-Bissau": "Guinea Bissau",
    "Korea, South": "South Korea",
    "Taiwan*": "Taiwan",
    "Tanzania": "United Republic of Tanzania",
    "Timor-Leste": "Timor Leste",
    "US": "United States of America",
    "West Bank and Gaza": "Palestine",
    "Turks and Caicos Islands": "Turks and Caicos islands",
    "Curacao": "Cura√ßao"
}

In [163]:
df["country"] = df["country"].apply(lambda x: correction_dict[x] if x in correction_dict.keys() else x)

In [164]:
dict_entries = set(code_dict.keys())
df_entries = set(df["country"].unique())
df_entries.difference(dict_entries)

{'Diamond Princess', 'MS Zaandam', 'Western Sahara'}

In [165]:
dict_entries.difference(df_entries)

{'Guam',
 'Guernsey',
 'Jersey',
 'Northern Mariana Islands',
 'Puerto Rico',
 'United States Virgin Islands'}

In [166]:
df["country_code"] = df["country"].map(code_dict)

In [167]:
len(df)

17313

In [168]:
df = df.dropna()

In [169]:
len(df)

17052

In [170]:
df

          date      country  confirmed  recovered  deaths country_code
0      1/22/20  Afghanistan        0.0        0.0     0.0          AFG
1      1/23/20  Afghanistan        0.0        0.0     0.0          AFG
2      1/24/20  Afghanistan        0.0        0.0     0.0          AFG
3      1/25/20  Afghanistan        0.0        0.0     0.0          AFG
4      1/26/20  Afghanistan        0.0        0.0     0.0          AFG
5      1/27/20  Afghanistan        0.0        0.0     0.0          AFG
6      1/28/20  Afghanistan        0.0        0.0     0.0          AFG
7      1/29/20  Afghanistan        0.0        0.0     0.0          AFG
8      1/30/20  Afghanistan        0.0        0.0     0.0          AFG
9      1/31/20  Afghanistan        0.0        0.0     0.0          AFG
10      2/1/20  Afghanistan        0.0        0.0     0.0          AFG
11      2/2/20  Afghanistan        0.0        0.0     0.0          AFG
12      2/3/20  Afghanistan        0.0        0.0     0.0          AFG
13      2/4/20  Afghanistan        0.0        0.0     0.0          AFG
14      2/5/20  Afghanistan        0.0        0.0     0.0          AFG
15      2/6/20  Afghanistan        0.0        0.0     0.0          AFG
16      2/7/20  Afghanistan        0.0        0.0     0.0          AFG
17      2/8/20  Afghanistan        0.0        0.0     0.0          AFG
18      2/9/20  Afghanistan        0.0        0.0     0.0          AFG
19     2/10/20  Afghanistan        0.0        0.0     0.0          AFG
20     2/11/20  Afghanistan        0.0        0.0     0.0          AFG
21     2/12/20  Afghanistan        0.0        0.0     0.0          AFG
22     2/13/20  Afghanistan        0.0        0.0     0.0          AFG
23     2/14/20  Afghanistan        0.0        0.0     0.0          AFG
24     2/15/20  Afghanistan        0.0        0.0     0.0          AFG
25     2/16/20  Afghanistan        0.0        0.0     0.0          AFG
26     2/17/20  Afghanistan        0.0        0.0     0.0          AFG
27     2/18/20  Afghanistan        0.0        0.0     0.0          AFG
28     2/19/20  Afghanistan        0.0        0.0     0.0          AFG
29     2/20/20  Afghanistan        0.0        0.0     0.0          AFG
...        ...          ...        ...        ...     ...          ...
17283  3/19/20     Zimbabwe        0.0        0.0     0.0          ZWE
17284  3/20/20     Zimbabwe        1.0        0.0     0.0          ZWE
17285  3/21/20     Zimbabwe        2.0        0.0     0.0          ZWE
17286  3/22/20     Zimbabwe        0.0        0.0     0.0          ZWE
17287  3/23/20     Zimbabwe        0.0        0.0     1.0          ZWE
17288  3/24/20     Zimbabwe        0.0        0.0     0.0          ZWE
17289  3/25/20     Zimbabwe        0.0        0.0     0.0          ZWE
17290  3/26/20     Zimbabwe        0.0        0.0     0.0          ZWE
17291  3/27/20     Zimbabwe        2.0        0.0     0.0          ZWE
17292  3/28/20     Zimbabwe        2.0        0.0     0.0          ZWE
17293  3/29/20     Zimbabwe        0.0        0.0     0.0          ZWE
17294  3/30/20     Zimbabwe        0.0        0.0     0.0          ZWE
17295  3/31/20     Zimbabwe        1.0        0.0     0.0          ZWE
17296   4/1/20     Zimbabwe        0.0        0.0     0.0          ZWE
17297   4/2/20     Zimbabwe        1.0        0.0     0.0          ZWE
17298   4/3/20     Zimbabwe        0.0        0.0     0.0          ZWE
17299   4/4/20     Zimbabwe        0.0        0.0     0.0          ZWE
17300   4/5/20     Zimbabwe        0.0        0.0     0.0          ZWE
17301   4/6/20     Zimbabwe        1.0        0.0     0.0          ZWE
17302   4/7/20     Zimbabwe        1.0        0.0     1.0          ZWE
17303   4/8/20     Zimbabwe        0.0        0.0     1.0          ZWE
17304   4/9/20     Zimbabwe        0.0        0.0     0.0          ZWE
17305  4/10/20     Zimbabwe        2.0        0.0     0.0          ZWE
17306  4/11/20     Zimbabwe        1.0        0.0     0.0          ZWE
17307  4/12/20     Zimbabwe        0.0        0.0     0.0          ZWE
17308  4/13/20     Zimbabwe        3.0        0.0     0.0          ZWE
17309  4/14/20     Zimbabwe        0.0        0.0     0.0          ZWE
17310  4/15/20     Zimbabwe        6.0        1.0     0.0          ZWE
17311  4/16/20     Zimbabwe        0.0        0.0     0.0          ZWE
17312  4/17/20     Zimbabwe        1.0        1.0     0.0          ZWE

[17052 rows x 6 columns]

In [171]:
df.to_csv("../Datasets/features_format.csv")