In [11]:
import pandas as pd

In [12]:
df_feat_format = pd.read_csv("~/SageMaker/Datasets/features_format.csv")
df_feat_format["date"] = pd.to_datetime(df_feat_format["date"])

df_feat_format.head()

,Unnamed: 0,date,country,confirmed,recovered,deaths,country_code
0,0,2020-01-22,Afghanistan,0.0,0.0,0.0,AFG
1,1,2020-01-23,Afghanistan,0.0,0.0,0.0,AFG
2,2,2020-01-24,Afghanistan,0.0,0.0,0.0,AFG
3,3,2020-01-25,Afghanistan,0.0,0.0,0.0,AFG
4,4,2020-01-26,Afghanistan,0.0,0.0,0.0,AFG

In [13]:
df_feat_format = df_feat_format.loc[:, ~df_feat_format.columns.str.contains("Unnamed")]
df_feat_format.head()

        date      country  confirmed  recovered  deaths country_code
0 2020-01-22  Afghanistan        0.0        0.0     0.0          AFG
1 2020-01-23  Afghanistan        0.0        0.0     0.0          AFG
2 2020-01-24  Afghanistan        0.0        0.0     0.0          AFG
3 2020-01-25  Afghanistan        0.0        0.0     0.0          AFG
4 2020-01-26  Afghanistan        0.0        0.0     0.0          AFG

In [14]:
df_crgt = pd.read_csv("~/SageMaker/Datasets/OxCGRT/OxCGRT-Processed.csv")
df_crgt["Date"] = pd.to_datetime(df_crgt["Date"])

del df_crgt["ConfirmedCases"]
del df_crgt["ConfirmedDeaths"]
del df_crgt["NewConfirmedCases"]
del df_crgt["NewConfirmedDeaths"]
del df_crgt["CountryName"]

df_crgt.head()

,CountryCode,Date,S1_School closing,S1_IsGeneral,S2_Workplace closing,S2_IsGeneral,S3_Cancel public events,S3_IsGeneral,S4_Close public transport,S4_IsGeneral,...,S6_IsGeneral,S7_International travel controls,S8_Fiscal measures,S9_Monetary measures,S10_Emergency investment in health care,S11_Investment in Vaccines,S12_Testing framework,S13_Contact tracing,StringencyIndex,StringencyIndexForDisplay
0,ABW,2020-01-01,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ABW,2020-01-02,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,ABW,2020-01-03,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,ABW,2020-01-04,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,ABW,2020-01-05,0.0,NaN,0.0,NaN,0.0,NaN,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
joined = df_feat_format.join(df_crgt.set_index(["CountryCode", "Date"]), on=["country_code", "date"], how="left").reset_index(drop=True)
joined = joined.loc[:, ~joined.columns.str.contains("Unnamed")]
joined.head()

,date,country,confirmed,recovered,deaths,country_code,S1_School closing,S1_IsGeneral,S2_Workplace closing,S2_IsGeneral,...,S6_IsGeneral,S7_International travel controls,S8_Fiscal measures,S9_Monetary measures,S10_Emergency investment in health care,S11_Investment in Vaccines,S12_Testing framework,S13_Contact tracing,StringencyIndex,StringencyIndexForDisplay
0,2020-01-22,Afghanistan,0.0,0.0,0.0,AFG,0.0,1.0,0.0,NaN,...,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1,2020-01-23,Afghanistan,0.0,0.0,0.0,AFG,0.0,1.0,0.0,NaN,...,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-24,Afghanistan,0.0,0.0,0.0,AFG,0.0,1.0,0.0,NaN,...,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-25,Afghanistan,0.0,0.0,0.0,AFG,0.0,1.0,0.0,NaN,...,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-26,Afghanistan,0.0,0.0,0.0,AFG,0.0,1.0,0.0,NaN,...,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
joined.to_csv("~/SageMaker/Datasets/features_format_cgrt_AI.csv", index=False)

In [16]:
missing_countries = set(df_crgt.CountryCode).difference(set(joined.country_code))

df = pd.read_csv("~/SageMaker/Datasets/OxCGRT/OxCGRT-Processed.csv")
df[df.CountryCode.isin(missing_countries)].CountryName.unique()

array(['Guam', 'Hong Kong', 'Lesotho', 'Macao', 'Puerto Rico', 'Kosovo'],
      dtype=object)